# Generated by Django 5.1.1 on 2024-11-11 21:21

import petstagram.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_groups_appuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', petstagram.accounts.managers.AppUserManager()),
            ],
        ),
    ]
